/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  serverBuildTarget: "vercel",
  // When running locally in development mode, we use the built in remix
  // server. This does not understand the vercel lambda module format,
  // so we default back to the standard build output.
  server: process.env.NODE_ENV === "development" ? undefined : "./server.js",
  ignoredRouteFiles: ["**/.*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "api/index.js",
  // publicPath: "/build/",
  serverDependenciesToBundle: [
    /^markdown.*/,
    /^rehype.*/,
    /^remark.*/,
    /^vfile.*/,
    /^unified.*/,
    /^mdast-util.*/,
    /^micromark.*/,
    "hast-util-whitespace",
    "mdast-util-definitions",
    "mdast-util-from-markdown",
    "mdast-util-to-hast",
    "micromark",
    "micromark-core-commonmark",
    "micromark-factory-destination",
    "micromark-factory-label",
    "micromark-factory-title",
    "micromark-factory-whitespace",
    "micromark-util-chunked",
    "micromark-util-classify-character",
    "micromark-util-combine-extensions",
    "micromark-util-encode",
    "micromark-util-html-tag-name",
    "micromark-util-normalize-identifier",
    "micromark-util-resolve-all",
    "micromark-util-sanitize-uri",
    "micromark-util-subtokenize",
    "react-markdown",
    "remark-parse",
    "remark-rehype",
    "unist-builder",
    "unist-util-generated",
    "unist-util-position",
    "trim-lines",
    "character-entities",
    "decode-named-character-reference",
    "longest-streak",
    "mdast-util-math",
    "mdast-util-to-markdown",
    "mdast-util-to-string",
    "micromark-extension-math",
    "micromark-factory-space",
    "micromark-util-character",
    "micromark-util-decode-numeric-character-reference",
    "micromark-util-decode-string",
    "micromark-util-symbol",
    "micromark-util-types",
    "remark-math",
    "zwitch",
    "bail",
    "comma-separated-tokens",
    "hast-util-from-parse5",
    "hast-util-is-element",
    "hast-util-parse-selector",
    "hast-util-to-text",
    "hastscript",
    "is-plain-obj",
    "property-information",
    "rehype-katex",
    "rehype-parse",
    "space-separated-tokens",
    "trough",
    "unified",
    "unist-util-find-after",
    "unist-util-is",
    "unist-util-remove-position",
    "unist-util-stringify-position",
    "unist-util-visit",
    "unist-util-visit-parents",
    "vfile",
    "vfile-location",
    "vfile-message",
    "web-namespaces",
  ],
};
